using System.Drawing.Printing;
namespace TechStore.App.Views;
partial class DashboardForm{Label summary=null!;DataGridView grid=null!;void InitializeComponent(){Text="Inicio";Width=900;Height=550;summary=new Label{Left=20,Top=20,Width=830,Height=70,Font=new Font("Segoe UI",12)};grid=Ui.Grid(20,110,840,360);Controls.AddRange([summary,new Label{Left=20,Top=90,Text="Stock bajo"},grid]);}}
partial class InventoryForm{DataGridView grid=null!;NumericUpDown amount=null!;void InitializeComponent(){Text="Inventario";Width=900;Height=560;grid=Ui.Grid(20,70,840,400);amount=new NumericUpDown{Left=120,Top=25,Minimum=-10000,Maximum=10000};var b=new Button{Left=260,Top=23,Text="Registrar ajuste",Width=130};b.Click+=Adjust;Controls.AddRange([new Label{Left=20,Top=28,Text="Ingreso/corrección:"},amount,b,grid]);}}
partial class AccountPaymentForm{ComboBox customers=null!;NumericUpDown amount=null!;TextBox description=null!;void InitializeComponent(){Text="Pago de cuenta corriente";Width=600;Height=330;customers=new ComboBox{Left=170,Top=30,Width=350,DropDownStyle=ComboBoxStyle.DropDownList};amount=new NumericUpDown{Left=170,Top=75,Width=180,Maximum=100000000,DecimalPlaces=2};description=new TextBox{Left=170,Top=120,Width=350};var b=new Button{Left=170,Top=175,Text="Registrar pago",Width=140};b.Click+=Pay;Controls.AddRange([new Label{Left=30,Top=34,Text="Cliente obligatorio:"},customers,new Label{Left=30,Top=79,Text="Importe:"},amount,new Label{Left=30,Top=124,Text="Descripción:"},description,b]);}}
partial class SaleForm{ComboBox customer=null!,branch=null!,seller=null!,product=null!,payment=null!,status=null!;NumericUpDown quantity=null!;TextBox notes=null!;DataGridView grid=null!;void InitializeComponent(){Text="Nueva venta";Width=980;Height=650;customer=Ui.Combo(130,25);branch=Ui.Combo(450,25);seller=Ui.Combo(750,25);product=Ui.Combo(130,75);quantity=new NumericUpDown{Left=450,Top=75,Minimum=1,Maximum=1000};payment=Ui.Combo(130,440);payment.DataSource=Enum.GetValues<Enums.PaymentMethod>();status=Ui.Combo(450,440);status.DataSource=Enum.GetValues<Enums.PaymentStatus>();notes=new TextBox{Left=130,Top=485,Width=650};grid=Ui.Grid(25,130,900,280);var add=new Button{Left=650,Top=73,Text="Agregar producto",Width=140};add.Click+=AddLine;var confirm=new Button{Left=750,Top=535,Text="Confirmar venta",Width=150};confirm.Click+=Confirm;Controls.AddRange([Ui.Label("Cliente:",25,28),customer,Ui.Label("Sucursal:",350,28),branch,Ui.Label("Vendedor:",650,28),seller,Ui.Label("Producto:",25,78),product,Ui.Label("Cantidad:",350,78),quantity,add,grid,Ui.Label("Método de pago:",25,444),payment,Ui.Label("Estado:",350,444),status,Ui.Label("Observaciones:",25,489),notes,confirm]);}}
partial class SalesHistoryForm{DataGridView grid=null!;void InitializeComponent(){Text="Historial de ventas";Width=1000;Height=600;grid=Ui.Grid(20,60,940,450);var b=new Button{Left=20,Top=20,Text="Anular venta seleccionada",Width=180};b.Click+=Cancel;Controls.AddRange([b,grid]);}}
partial class ReportsForm{DataGridView sales=null!,products=null!,accounts=null!;void InitializeComponent(){Text="Reportes";Width=950;Height=600;var tabs=new TabControl{Dock=DockStyle.Fill};sales=Ui.Grid(5,5,900,500);products=Ui.Grid(5,5,900,500);accounts=Ui.Grid(5,5,900,500);foreach(var pair in new[]{("Ventas por sucursal",sales),("Productos más vendidos",products),("Cuentas corrientes",accounts)}){var page=new TabPage(pair.Item1);page.Controls.Add(pair.Item2);tabs.TabPages.Add(page);}Controls.Add(tabs);}}
partial class InvoiceForm{TextBox text=null!;PrintDocument document=null!;void InitializeComponent(){Text="Factura";Width=800;Height=650;document=new PrintDocument();text=new TextBox{Left=20,Top=20,Width=740,Height=500,Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Vertical,Font=new Font("Consolas",10)};var preview=new Button{Left=20,Top=545,Text="Vista previa",Width=120};preview.Click+=Preview;var print=new Button{Left=150,Top=545,Text="Imprimir",Width=120};print.Click+=Print;var close=new Button{Left=640,Top=545,Text="Cerrar",Width=120};close.Click+=(_,_)=>Close();Controls.AddRange([text,preview,print,close]);}}
static class Ui{public static DataGridView Grid(int x,int y,int w,int h)=>new(){Left=x,Top=y,Width=w,Height=h,ReadOnly=true,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,SelectionMode=DataGridViewSelectionMode.FullRowSelect};public static ComboBox Combo(int x,int y)=>new(){Left=x,Top=y,Width=190,DropDownStyle=ComboBoxStyle.DropDownList};public static Label Label(string text,int x,int y)=>new(){Text=text,Left=x,Top=y,AutoSize=true};}
