using TechStore.App.Enums;
namespace TechStore.App.Models;
public class Category { public int Id {get;set;} public string Name {get;set;}=""; public string? Description {get;set;} public bool IsActive {get;set;}=true; public List<Product> Products {get;set;}=[]; }
public class Product { public int Id {get;set;} public string Code {get;set;}=""; public string Name {get;set;}=""; public string? Description {get;set;} public int CategoryId {get;set;} public Category Category {get;set;}=null!; public decimal Price {get;set;} public bool IsActive {get;set;}=true; public DateTime CreatedAt {get;set;}=DateTime.Now; public DateTime UpdatedAt {get;set;}=DateTime.Now; }
public class Branch { public int Id {get;set;} public string Name {get;set;}=""; public string Address {get;set;}=""; public string Phone {get;set;}=""; public bool IsActive {get;set;}=true; }
public class Inventory { public int Id {get;set;} public int ProductId {get;set;} public Product Product {get;set;}=null!; public int BranchId {get;set;} public Branch Branch {get;set;}=null!; public int Stock {get;set;} public int MinimumStock {get;set;} }
public class Customer { public int Id {get;set;} public string? DocumentNumber {get;set;} public string BusinessName {get;set;}=""; public string? Email {get;set;} public string? Phone {get;set;} public string? Address {get;set;} public CustomerType CustomerType {get;set;} public decimal DiscountPercentage {get;set;} public decimal CurrentAccountBalance {get;set;} public bool IsActive {get;set;}=true; public DateTime CreatedAt {get;set;}=DateTime.Now; }
public class Seller { public int Id {get;set;} public string Name {get;set;}=""; public string DocumentNumber {get;set;}=""; public string? Email {get;set;} public string? Phone {get;set;} public bool IsActive {get;set;}=true; }
public class Sale { public int Id {get;set;} public string InvoiceNumber {get;set;}=""; public DateTime Date {get;set;} public int CustomerId {get;set;} public Customer Customer {get;set;}=null!; public int BranchId {get;set;} public Branch Branch {get;set;}=null!; public int SellerId {get;set;} public Seller Seller {get;set;}=null!; public decimal Subtotal {get;set;} public decimal DiscountAmount {get;set;} public decimal Total {get;set;} public PaymentMethod PaymentMethod {get;set;} public PaymentStatus PaymentStatus {get;set;} public string? Notes {get;set;} public bool IsCancelled {get;set;} public List<SaleItem> Items {get;set;}=[]; }
public class SaleItem { public int Id {get;set;} public int SaleId {get;set;} public Sale Sale {get;set;}=null!; public int ProductId {get;set;} public Product Product {get;set;}=null!; public int Quantity {get;set;} public decimal UnitPrice {get;set;} public decimal Subtotal {get;set;} }
public class CurrentAccountMovement { public int Id {get;set;} public int CustomerId {get;set;} public Customer Customer {get;set;}=null!; public int? SaleId {get;set;} public Sale? Sale {get;set;} public DateTime Date {get;set;} public CurrentAccountMovementType MovementType {get;set;} public string Description {get;set;}=""; public decimal Debit {get;set;} public decimal Credit {get;set;} public decimal Balance {get;set;} }
