/* Ejecutar conectado a master. Esquema exacto utilizado por TechStore.App. */
IF DB_ID(N'TechStoreDB') IS NULL CREATE DATABASE TechStoreDB;
GO
USE TechStoreDB;
GO
IF OBJECT_ID(N'dbo.Categories',N'U') IS NOT NULL THROW 50000,N'TechStoreDB ya contiene el esquema. Use 99-Recrear-TechStoreDB.sql solamente en desarrollo.',1;

CREATE TABLE dbo.Branches(Id int IDENTITY PRIMARY KEY,Name nvarchar(100) NOT NULL,Address nvarchar(200) NOT NULL,Phone nvarchar(30) NOT NULL,IsActive bit NOT NULL CONSTRAINT DF_Branches_IsActive DEFAULT 1);
CREATE TABLE dbo.Categories(Id int IDENTITY PRIMARY KEY,Name nvarchar(80) NOT NULL,Description nvarchar(250) NULL,IsActive bit NOT NULL CONSTRAINT DF_Categories_IsActive DEFAULT 1);
CREATE UNIQUE INDEX UX_Categories_Name ON dbo.Categories(Name);
CREATE TABLE dbo.Customers(Id int IDENTITY PRIMARY KEY,DocumentNumber nvarchar(30) NULL,BusinessName nvarchar(150) NOT NULL,Email nvarchar(150) NULL,Phone nvarchar(30) NULL,Address nvarchar(200) NULL,CustomerType int NOT NULL,DiscountPercentage decimal(5,2) NOT NULL CONSTRAINT DF_Customers_Discount DEFAULT 0,CurrentAccountBalance decimal(18,2) NOT NULL CONSTRAINT DF_Customers_Balance DEFAULT 0,IsActive bit NOT NULL CONSTRAINT DF_Customers_IsActive DEFAULT 1,CreatedAt datetime2 NOT NULL CONSTRAINT DF_Customers_Created DEFAULT SYSDATETIME(),CONSTRAINT CK_Customers_Discount CHECK(DiscountPercentage BETWEEN 0 AND 100),CONSTRAINT CK_Customers_Balance CHECK(CurrentAccountBalance>=0));
CREATE UNIQUE INDEX UX_Customers_Document ON dbo.Customers(DocumentNumber) WHERE DocumentNumber IS NOT NULL;
CREATE TABLE dbo.Sellers(Id int IDENTITY PRIMARY KEY,Name nvarchar(120) NOT NULL,DocumentNumber nvarchar(30) NOT NULL,Email nvarchar(150) NULL,Phone nvarchar(30) NULL,IsActive bit NOT NULL CONSTRAINT DF_Sellers_IsActive DEFAULT 1);
CREATE UNIQUE INDEX UX_Sellers_Document ON dbo.Sellers(DocumentNumber);
CREATE TABLE dbo.Products(Id int IDENTITY PRIMARY KEY,Code nvarchar(30) NOT NULL,Name nvarchar(120) NOT NULL,Description nvarchar(250) NULL,CategoryId int NOT NULL,Price decimal(18,2) NOT NULL,IsActive bit NOT NULL CONSTRAINT DF_Products_IsActive DEFAULT 1,CreatedAt datetime2 NOT NULL CONSTRAINT DF_Products_Created DEFAULT SYSDATETIME(),UpdatedAt datetime2 NOT NULL CONSTRAINT DF_Products_Updated DEFAULT SYSDATETIME(),CONSTRAINT FK_Products_Categories FOREIGN KEY(CategoryId) REFERENCES dbo.Categories(Id),CONSTRAINT CK_Products_Price CHECK(Price>0));
CREATE UNIQUE INDEX UX_Products_Code ON dbo.Products(Code);
CREATE TABLE dbo.Inventories(Id int IDENTITY PRIMARY KEY,ProductId int NOT NULL,BranchId int NOT NULL,Stock int NOT NULL CONSTRAINT DF_Inventories_Stock DEFAULT 0,MinimumStock int NOT NULL CONSTRAINT DF_Inventories_Minimum DEFAULT 0,CONSTRAINT FK_Inventories_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(Id),CONSTRAINT FK_Inventories_Branches FOREIGN KEY(BranchId) REFERENCES dbo.Branches(Id),CONSTRAINT UQ_Inventories_ProductBranch UNIQUE(ProductId,BranchId),CONSTRAINT CK_Inventories_Stock CHECK(Stock>=0 AND MinimumStock>=0));
CREATE TABLE dbo.Sales(Id int IDENTITY PRIMARY KEY,InvoiceNumber nvarchar(30) NOT NULL,Date datetime2 NOT NULL,CustomerId int NOT NULL,BranchId int NOT NULL,SellerId int NOT NULL,Subtotal decimal(18,2) NOT NULL,DiscountAmount decimal(18,2) NOT NULL,Total decimal(18,2) NOT NULL,PaymentMethod int NOT NULL,PaymentStatus int NOT NULL,Notes nvarchar(500) NULL,IsCancelled bit NOT NULL CONSTRAINT DF_Sales_IsCancelled DEFAULT 0,CONSTRAINT FK_Sales_Customers FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(Id),CONSTRAINT FK_Sales_Branches FOREIGN KEY(BranchId) REFERENCES dbo.Branches(Id),CONSTRAINT FK_Sales_Sellers FOREIGN KEY(SellerId) REFERENCES dbo.Sellers(Id),CONSTRAINT CK_Sales_Totals CHECK(Subtotal>=0 AND DiscountAmount>=0 AND Total=Subtotal-DiscountAmount));
CREATE UNIQUE INDEX UX_Sales_Invoice ON dbo.Sales(InvoiceNumber);
CREATE TABLE dbo.SaleItems(Id int IDENTITY PRIMARY KEY,SaleId int NOT NULL,ProductId int NOT NULL,Quantity int NOT NULL,UnitPrice decimal(18,2) NOT NULL,Subtotal decimal(18,2) NOT NULL,CONSTRAINT FK_SaleItems_Sales FOREIGN KEY(SaleId) REFERENCES dbo.Sales(Id) ON DELETE CASCADE,CONSTRAINT FK_SaleItems_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(Id),CONSTRAINT CK_SaleItems_Values CHECK(Quantity>0 AND UnitPrice>0 AND Subtotal=Quantity*UnitPrice));
CREATE TABLE dbo.CurrentAccountMovements(Id int IDENTITY PRIMARY KEY,CustomerId int NOT NULL,SaleId int NULL,Date datetime2 NOT NULL,MovementType int NOT NULL,Description nvarchar(250) NOT NULL,Debit decimal(18,2) NOT NULL CONSTRAINT DF_Movements_Debit DEFAULT 0,Credit decimal(18,2) NOT NULL CONSTRAINT DF_Movements_Credit DEFAULT 0,Balance decimal(18,2) NOT NULL,CONSTRAINT FK_Movements_Customers FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(Id),CONSTRAINT FK_Movements_Sales FOREIGN KEY(SaleId) REFERENCES dbo.Sales(Id),CONSTRAINT CK_Movements_Amounts CHECK(Debit>=0 AND Credit>=0 AND Balance>=0));
CREATE INDEX IX_Sales_Date ON dbo.Sales(Date); CREATE INDEX IX_SaleItems_Product ON dbo.SaleItems(ProductId); CREATE INDEX IX_Movements_CustomerDate ON dbo.CurrentAccountMovements(CustomerId,Date);
GO
