/* TechStoreDB - SQL Server 2019+. Idempotente a nivel de base nueva. */
IF DB_ID(N'TechStoreDB') IS NULL CREATE DATABASE TechStoreDB;
GO
USE TechStoreDB;
GO
CREATE TABLE dbo.Sucursales(IdSucursal int IDENTITY PRIMARY KEY,Nombre nvarchar(100) NOT NULL,Direccion nvarchar(200) NOT NULL,Telefono nvarchar(30) NOT NULL,Activa bit NOT NULL CONSTRAINT DF_Sucursales_Activa DEFAULT 1);
CREATE TABLE dbo.Categorias(IdCategoria int IDENTITY PRIMARY KEY,Nombre nvarchar(80) NOT NULL UNIQUE,Descripcion nvarchar(250) NULL,Activa bit NOT NULL CONSTRAINT DF_Categorias_Activa DEFAULT 1);
CREATE TABLE dbo.Productos(Codigo nvarchar(30) PRIMARY KEY,Descripcion nvarchar(120) NOT NULL,IdCategoria int NOT NULL,Precio decimal(18,2) NOT NULL CHECK(Precio>0),Activo bit NOT NULL CONSTRAINT DF_Productos_Activo DEFAULT 1,CONSTRAINT FK_Productos_Categorias FOREIGN KEY(IdCategoria) REFERENCES dbo.Categorias(IdCategoria));
CREATE TABLE dbo.Clientes(IdCliente int IDENTITY PRIMARY KEY,CUIT nvarchar(20) NULL,NombreRazonSocial nvarchar(150) NOT NULL,Email nvarchar(150) NULL,Telefono nvarchar(30) NULL,Direccion nvarchar(200) NULL,DescuentoPorcentaje decimal(5,2) NOT NULL CONSTRAINT DF_Clientes_Descuento DEFAULT 0 CHECK(DescuentoPorcentaje BETWEEN 0 AND 100),Activo bit NOT NULL CONSTRAINT DF_Clientes_Activo DEFAULT 1);
CREATE UNIQUE INDEX UX_Clientes_CUIT ON dbo.Clientes(CUIT) WHERE CUIT IS NOT NULL;
CREATE TABLE dbo.Vendedores(IdVendedor int IDENTITY PRIMARY KEY,Nombre nvarchar(120) NOT NULL,Legajo nvarchar(30) NOT NULL UNIQUE,IdSucursal int NOT NULL,Email nvarchar(150) NULL,Telefono nvarchar(30) NULL,Activo bit NOT NULL CONSTRAINT DF_Vendedores_Activo DEFAULT 1,CONSTRAINT FK_Vendedores_Sucursales FOREIGN KEY(IdSucursal) REFERENCES dbo.Sucursales(IdSucursal));
CREATE TABLE dbo.StockSucursal(IdSucursal int NOT NULL,CodigoProducto nvarchar(30) NOT NULL,Stock int NOT NULL CHECK(Stock>=0),StockMinimo int NOT NULL CONSTRAINT DF_Stock_Minimo DEFAULT 0 CHECK(StockMinimo>=0),CONSTRAINT PK_StockSucursal PRIMARY KEY(IdSucursal,CodigoProducto),CONSTRAINT FK_Stock_Sucursal FOREIGN KEY(IdSucursal) REFERENCES dbo.Sucursales(IdSucursal),CONSTRAINT FK_Stock_Producto FOREIGN KEY(CodigoProducto) REFERENCES dbo.Productos(Codigo));
CREATE TABLE dbo.Ventas(IdVenta int IDENTITY PRIMARY KEY,NumeroFactura AS ('FAC-'+RIGHT(REPLICATE('0',8)+CONVERT(varchar(8),IdVenta),8)) PERSISTED,Fecha datetime2 NOT NULL CONSTRAINT DF_Ventas_Fecha DEFAULT SYSDATETIME(),IdSucursal int NOT NULL,IdCliente int NOT NULL,IdVendedor int NOT NULL,TotalBruto decimal(18,2) NOT NULL CHECK(TotalBruto>=0),DescuentoTotal decimal(18,2) NOT NULL CHECK(DescuentoTotal>=0),TotalNeto AS (TotalBruto-DescuentoTotal) PERSISTED,MetodoPago nvarchar(30) NOT NULL CHECK(MetodoPago IN(N'Efectivo',N'Tarjeta',N'Transferencia',N'Cuenta Corriente',N'CC')),EstadoPago nvarchar(30) NOT NULL,Observaciones nvarchar(500) NULL,Anulada bit NOT NULL CONSTRAINT DF_Ventas_Anulada DEFAULT 0,CONSTRAINT FK_Ventas_Sucursal FOREIGN KEY(IdSucursal) REFERENCES dbo.Sucursales(IdSucursal),CONSTRAINT FK_Ventas_Cliente FOREIGN KEY(IdCliente) REFERENCES dbo.Clientes(IdCliente),CONSTRAINT FK_Ventas_Vendedor FOREIGN KEY(IdVendedor) REFERENCES dbo.Vendedores(IdVendedor),CONSTRAINT CK_Ventas_Descuento CHECK(DescuentoTotal<=TotalBruto));
CREATE UNIQUE INDEX UX_Ventas_NumeroFactura ON dbo.Ventas(NumeroFactura);
CREATE TABLE dbo.DetalleVenta(IdDetalle int IDENTITY PRIMARY KEY,IdVenta int NOT NULL,CodigoProducto nvarchar(30) NOT NULL,Cantidad int NOT NULL CHECK(Cantidad>0),PrecioUnitario decimal(18,2) NOT NULL CHECK(PrecioUnitario>0),DescuentoLinea decimal(18,2) NOT NULL CONSTRAINT DF_Detalle_Descuento DEFAULT 0 CHECK(DescuentoLinea>=0),Subtotal AS ((Cantidad*PrecioUnitario)-DescuentoLinea) PERSISTED,CONSTRAINT FK_Detalle_Venta FOREIGN KEY(IdVenta) REFERENCES dbo.Ventas(IdVenta),CONSTRAINT FK_Detalle_Producto FOREIGN KEY(CodigoProducto) REFERENCES dbo.Productos(Codigo));
CREATE TABLE dbo.MovimientosCuentaCorriente(IdMovimiento int IDENTITY PRIMARY KEY,IdCliente int NOT NULL,IdVenta int NULL,Fecha datetime2 NOT NULL CONSTRAINT DF_Movimientos_Fecha DEFAULT SYSDATETIME(),Tipo nvarchar(20) NOT NULL CHECK(Tipo IN(N'Cargo',N'Pago',N'Anulación')),Descripcion nvarchar(250) NOT NULL,Debe decimal(18,2) NOT NULL CONSTRAINT DF_Movimientos_Debe DEFAULT 0,Haber decimal(18,2) NOT NULL CONSTRAINT DF_Movimientos_Haber DEFAULT 0,CONSTRAINT FK_Movimientos_Cliente FOREIGN KEY(IdCliente) REFERENCES dbo.Clientes(IdCliente),CONSTRAINT FK_Movimientos_Venta FOREIGN KEY(IdVenta) REFERENCES dbo.Ventas(IdVenta),CONSTRAINT CK_Movimientos_Importes CHECK(Debe>=0 AND Haber>=0 AND (Debe>0 OR Haber>0)));
GO
