using Xunit;
using Microsoft.Data.Sqlite;using Microsoft.EntityFrameworkCore;using TechStore.App.Data;using TechStore.App.DTOs;using TechStore.App.Enums;using TechStore.App.Models;using TechStore.App.Services;
namespace TechStore.Tests;
public class BusinessServicesTests:IDisposable{readonly SqliteConnection connection=new("DataSource=:memory:");readonly TechStoreDbContext db;public BusinessServicesTests(){connection.Open();db=new(new DbContextOptionsBuilder<TechStoreDbContext>().UseSqlite(connection).Options);db.Database.EnsureCreated();Seed();}void Seed(){var c=new Category{Name="Cat"};var p=new Product{Code="P1",Name="Producto",Category=c,Price=100};var b=new Branch{Name="Central",Address="A",Phone="1"};var customer=new Customer{BusinessName="Mayorista",CustomerType=CustomerType.Mayorista,DiscountPercentage=10};var seller=new Seller{Name="Ana",DocumentNumber="1"};db.AddRange(c,p,b,customer,seller);db.SaveChanges();db.Add(new Inventory{ProductId=p.Id,BranchId=b.Id,Stock=10,MinimumStock=2});db.SaveChanges();}
[Fact]public void CalculatesSubtotal()=>Assert.Equal(250,SaleService.CalculateSubtotal([(100m,2),(50m,1)]));[Fact]public void CalculatesWholesaleDiscount()=>Assert.Equal(10,SaleService.CalculateDiscount(100,10));[Fact]public void CalculatesTotal()=>Assert.Equal(90,SaleService.CalculateTotal(100,10));
[Fact]public async Task RejectsInsufficientStock(){var req=Request(11);await Assert.ThrowsAsync<InvalidOperationException>(()=>new SaleService(db).CreateAsync(req));Assert.Equal(10,db.Inventories.Single().Stock);}
[Fact]public async Task SaleDiscountsStockAndRegistersAccount(){var sale=await new SaleService(db).CreateAsync(Request(2));Assert.Equal(8,db.Inventories.Single().Stock);Assert.Equal(180,sale.Total);Assert.Equal(180,db.Customers.Single().CurrentAccountBalance);Assert.Single(db.CurrentAccountMovements);}
[Fact]public async Task PaymentReducesBalance(){await new SaleService(db).CreateAsync(Request(2));await new AccountService(db).RegisterPaymentAsync(db.Customers.Single().Id,80,"Pago");Assert.Equal(100,db.Customers.Single().CurrentAccountBalance);}
[Fact]public async Task CancellationRestoresStock(){var sale=await new SaleService(db).CreateAsync(Request(2));await new SaleService(db).CancelAsync(sale.Id);Assert.Equal(10,db.Inventories.Single().Stock);Assert.True(db.Sales.Single().IsCancelled);Assert.Equal(0,db.Customers.Single().CurrentAccountBalance);}
CreateSaleRequest Request(int quantity)=>new(db.Customers.Single().Id,db.Branches.Single().Id,db.Sellers.Single().Id,DateTime.Now,PaymentMethod.CuentaCorriente,PaymentStatus.Pendiente,null,[new(db.Products.Single().Id,quantity)]);public void Dispose(){db.Dispose();connection.Dispose();}}
