using Microsoft.EntityFrameworkCore;using TechStore.App.Data;using TechStore.App.DTOs;using TechStore.App.Enums;using TechStore.App.Models;
namespace TechStore.App.Services;
public class SaleService(TechStoreDbContext db){
 public static decimal CalculateSubtotal(IEnumerable<(decimal price,int quantity)> lines)=>lines.Sum(x=>x.price*x.quantity); public static decimal CalculateDiscount(decimal subtotal,decimal percentage)=>Math.Round(subtotal*percentage/100,2); public static decimal CalculateTotal(decimal subtotal,decimal discount)=>subtotal-discount;
 public async Task<Sale> CreateAsync(CreateSaleRequest request){if(request.Items.Count==0)throw new InvalidOperationException("La venta debe contener al menos un producto.");if(request.Items.Any(x=>x.Quantity<=0))throw new InvalidOperationException("Las cantidades deben ser mayores que cero.");
  await using var tx=await db.Database.BeginTransactionAsync(); var customer=await db.Customers.SingleOrDefaultAsync(x=>x.Id==request.CustomerId&&x.IsActive)??throw new InvalidOperationException("Cliente inválido o inactivo."); if(!await db.Branches.AnyAsync(x=>x.Id==request.BranchId&&x.IsActive))throw new InvalidOperationException("Sucursal inválida.");if(!await db.Sellers.AnyAsync(x=>x.Id==request.SellerId&&x.IsActive))throw new InvalidOperationException("Vendedor inválido.");
  var ids=request.Items.Select(x=>x.ProductId).Distinct().ToArray();var products=await db.Products.Where(x=>ids.Contains(x.Id)&&x.IsActive).ToDictionaryAsync(x=>x.Id);var stocks=await db.Inventories.Where(x=>x.BranchId==request.BranchId&&ids.Contains(x.ProductId)).ToDictionaryAsync(x=>x.ProductId);var lines=new List<SaleItem>();
  foreach(var item in request.Items){if(!products.TryGetValue(item.ProductId,out var product)||!stocks.TryGetValue(item.ProductId,out var stock))throw new InvalidOperationException("Producto no disponible.");if(stock.Stock<item.Quantity)throw new InvalidOperationException($"Stock insuficiente para {product.Name}.");stock.Stock-=item.Quantity;lines.Add(new SaleItem{ProductId=product.Id,Quantity=item.Quantity,UnitPrice=product.Price,Subtotal=product.Price*item.Quantity});}
  var subtotal=lines.Sum(x=>x.Subtotal);var discount=CalculateDiscount(subtotal,customer.DiscountPercentage);var sale=new Sale{InvoiceNumber=await NextInvoiceAsync(),Date=request.Date,CustomerId=customer.Id,BranchId=request.BranchId,SellerId=request.SellerId,Subtotal=subtotal,DiscountAmount=discount,Total=subtotal-discount,PaymentMethod=request.PaymentMethod,PaymentStatus=request.PaymentStatus,Notes=request.Notes,Items=lines};db.Sales.Add(sale);
  if(request.PaymentMethod==PaymentMethod.CuentaCorriente||request.PaymentStatus!=PaymentStatus.Pagado){customer.CurrentAccountBalance+=sale.Total;db.CurrentAccountMovements.Add(new(){Customer=customer,Sale=sale,Date=DateTime.Now,MovementType=CurrentAccountMovementType.Cargo,Description=$"Venta {sale.InvoiceNumber}",Debit=sale.Total,Balance=customer.CurrentAccountBalance});}await db.SaveChangesAsync();await tx.CommitAsync();return sale; }
 async Task<string> NextInvoiceAsync(){var next=(await db.Sales.MaxAsync(x=>(int?)x.Id)??0)+1;return $"FAC-{next:00000000}";}
 public async Task CancelAsync(int id){await using var tx=await db.Database.BeginTransactionAsync();var sale=await db.Sales.Include(x=>x.Items).Include(x=>x.Customer).SingleAsync(x=>x.Id==id);if(sale.IsCancelled)throw new InvalidOperationException("La venta ya está anulada.");foreach(var line in sale.Items)(await db.Inventories.SingleAsync(x=>x.BranchId==sale.BranchId&&x.ProductId==line.ProductId)).Stock+=line.Quantity;var charge=await db.CurrentAccountMovements.FirstOrDefaultAsync(x=>x.SaleId==id&&x.MovementType==CurrentAccountMovementType.Cargo);if(charge!=null){var amount=Math.Min(charge.Debit,sale.Customer.CurrentAccountBalance);sale.Customer.CurrentAccountBalance-=amount;db.Add(new CurrentAccountMovement{CustomerId=sale.CustomerId,SaleId=sale.Id,Date=DateTime.Now,MovementType=CurrentAccountMovementType.Anulacion,Description=$"Anulación {sale.InvoiceNumber}",Credit=amount,Balance=sale.Customer.CurrentAccountBalance});}sale.IsCancelled=true;await db.SaveChangesAsync();await tx.CommitAsync();}
}
